apiVersion: apps/v1
kind: Deployment
metadata:
  name: tel-deployment
spec:
  selector:
    matchLabels:
      app: tel
  replicas: 2
  template:
    metadata:
      labels:
        app: tel
    spec:
      containers:
        - name: tel-app
          image: bsdemon/tel-app:0.0.3
          ports:
            - containerPort: 8000